# Generated by Django 5.1.1 on 2024-10-02 12:04

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                default="49,24", max_length=63
            ),
        ),
    ]
