# Generated by Django 5.1.1 on 2024-10-04 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0003_meetups_news_users_delete_meetup_news_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetups",
            options={"verbose_name_plural": "Meetups"},
        ),
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name_plural": "News"},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name_plural": "Users"},
        ),
    ]
