# Generated by Django 5.1.1 on 2024-10-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0005_remove_meetups_is_online"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="is_online",
            new_name="is_admin",
        ),
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
