# Generated by Django 5.1.1 on 2024-10-05 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0006_rename_is_online_users_is_admin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meetups",
            old_name="author",
            new_name="organizer",
        ),
    ]
