# Generated by Django 5.1.1 on 2024-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0009_populate_news_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
