# Generated by Django 5.1.1 on 2024-10-05 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0010_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_set",
                to="meetups.users",
            ),
        ),
    ]
