# Generated by Django 5.1.1 on 2024-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0013_alter_meetups_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetups",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
