# Generated by Django 5.1.1 on 2024-11-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0020_users_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_admin',
            new_name='is_superuser',
        ),
    ]
