# Generated by Django 5.1.1 on 2024-11-13 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="last_name",
            new_name="surname",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, upload_to="user_images"),
        ),
    ]
