# Generated by Django 5.1.1 on 2025-01-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_first_name_customuser_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, default="default-pfp.png", upload_to="user_images"
            ),
        ),
    ]
